# Generated by Django 4.1 on 2023-05-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('contents', models.TextField()),
                ('date', models.DateField()),
                ('like_counter', models.IntegerField(default=0)),
                ('com_counter', models.IntegerField(default=0)),
                ('jpg', models.ImageField(blank=True, null=True, upload_to='static/jpg')),
            ],
        ),
    ]
